version: "3"
services:
  esia:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: ${APP_NAME:?esia_container}
    volumes:
      - "${WORK_DIRECTORY}/src:/root"
